### ISSUE TITLE
Unable to close client

### ISSUE THREAD

**Issue by ShaneMcC** [DMDirc/Plugins#512]
Can't seem to reproduce, but I was trying to close the client mid-way through it connecting to my bouncer, and then it stopped being able to close. Got this error on the console:

    Error during invocation of message handler. There might be an access rights problem. Do you use non public inner classes?
    java.lang.IllegalArgumentException
            at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
            at com.dmdirc.ui.WindowManager.removeWindow(WindowManager.java:264)
            at com.dmdirc.ui.WindowManager.frameClosing(WindowManager.java:420)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at net.engio.mbassy.dispatch.ReflectiveHandlerInvocation.invoke(ReflectiveHandlerInvocation.java:29)
            at net.engio.mbassy.dispatch.MessageDispatcher.dispatch(MessageDispatcher.java:30)
            at net.engio.mbassy.dispatch.FilteredMessageDispatcher.dispatch(FilteredMessageDispatcher.java:42)
            at net.engio.mbassy.subscription.Subscription.publish(Subscription.java:72)
            at net.engio.mbassy.bus.MessagePublication.execute(MessagePublication.java:49)
            at net.engio.mbassy.bus.MBassador.publish(MBassador.java:66)
            at com.dmdirc.DMDircMBassador.publish(DMDircMBassador.java:74)
            at com.dmdirc.FrameContainer.close(FrameContainer.java:212)
            at com.dmdirc.ServerManager.closeAll(ServerManager.java:156)
            at com.dmdirc.addons.ui_swing.QuitWorker.doInBackground(QuitWorker.java:75)
            at com.dmdirc.addons.ui_swing.QuitWorker.doInBackground(QuitWorker.java:38)
            at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at javax.swing.SwingWorker.run(SwingWorker.java:334)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

**Comment by csmith** [comment]
(Why is this in plugins?)
